spring.application.name=sbi
spring.datasource.url = ${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.data-source-properties.sslmode=require
jwt.secret=randomAssJwtSecretKeyPleaseWork🥺
jwt.expiration=3600000
application.port=${PORT:8080}